# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'compiler.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(888, 649)
        MainWindow.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        Ui_MainWindow.INPUT = QtWidgets.QTextEdit(self.centralwidget)
        Ui_MainWindow.INPUT.setGeometry(QtCore.QRect(50, 80, 831, 311))
        Ui_MainWindow.INPUT.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"")
        Ui_MainWindow.INPUT.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        Ui_MainWindow.INPUT.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        Ui_MainWindow.INPUT.setObjectName("INPUT")
        Ui_MainWindow.OUTPUT = QtWidgets.QTextEdit(self.centralwidget)
        Ui_MainWindow.OUTPUT.setGeometry(QtCore.QRect(10, 400, 871, 221))
        Ui_MainWindow.OUTPUT.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"")
        Ui_MainWindow.OUTPUT.setReadOnly(True)
        Ui_MainWindow.OUTPUT.setPlaceholderText("")
        Ui_MainWindow.OUTPUT.setObjectName("OUTPUT")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, -10, 871, 81))
        self.frame.setStyleSheet("background-color: rgb(52, 101, 164);\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 10, 201, 61))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 italic 35pt \"Ubuntu\";\n"
"")
        self.label.setObjectName("label")
        Ui_MainWindow.LEXICAL = QtWidgets.QPushButton(self.frame)
        Ui_MainWindow.LEXICAL.setGeometry(QtCore.QRect(490, 20, 181, 51))
        Ui_MainWindow.LEXICAL.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        Ui_MainWindow.LEXICAL.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"")
        Ui_MainWindow.LEXICAL.setObjectName("LEXICAL")
        Ui_MainWindow.SYNTAX = QtWidgets.QPushButton(self.frame)
        Ui_MainWindow.SYNTAX.setGeometry(QtCore.QRect(680, 20, 181, 51))
        Ui_MainWindow.SYNTAX.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        Ui_MainWindow.SYNTAX.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"")
        Ui_MainWindow.SYNTAX.setObjectName("SYNTAX")
        Ui_MainWindow.INPUT_2 = QtWidgets.QTextEdit(self.centralwidget)
        Ui_MainWindow.INPUT_2.setGeometry(QtCore.QRect(10, 80, 31, 311))
        Ui_MainWindow.INPUT_2.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 5px;\n"
"\n"
"")
        Ui_MainWindow.INPUT_2.setLineWidth(2)
        Ui_MainWindow.INPUT_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        Ui_MainWindow.INPUT_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        Ui_MainWindow.INPUT_2.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        Ui_MainWindow.INPUT_2.setLineWrapColumnOrWidth(3)
        Ui_MainWindow.INPUT_2.setReadOnly(True)
        Ui_MainWindow.INPUT_2.setPlaceholderText("")
        Ui_MainWindow.INPUT_2.setObjectName("INPUT_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 888, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew_File = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Compiler /icons/add-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_File.setIcon(icon)
        self.actionNew_File.setObjectName("actionNew_File")
        self.actionNew_Windows = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Compiler /icons/new-page.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_Windows.setIcon(icon1)
        self.actionNew_Windows.setObjectName("actionNew_Windows")
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Compiler /icons/open-folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_File.setIcon(icon2)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionSave_File = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Compiler /icons/floppy-disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_File.setIcon(icon3)
        self.actionSave_File.setObjectName("actionSave_File")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Compiler /icons/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon4)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Compiler /icons/paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon5)
        self.actionPaste.setObjectName("actionPaste")
        self.actionCut = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Compiler /icons/cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon6)
        self.actionCut.setObjectName("actionCut")
        self.menuFile.addAction(self.actionNew_File)
        self.menuFile.addAction(self.actionNew_Windows)
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addAction(self.actionSave_File)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionCut)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        Ui_MainWindow.INPUT.setPlaceholderText(_translate("MainWindow", "Write Your Code Here..."))
        self.label.setText(_translate("MainWindow", "Compiler"))
        Ui_MainWindow.LEXICAL.setText(_translate("MainWindow", "Analyse Lexical"))
        Ui_MainWindow.SYNTAX.setText(_translate("MainWindow", "Analyse Syntaxique"))
        Ui_MainWindow.INPUT_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">|1</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">|2</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">|3</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">|4</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">|5</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">|6</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">|7</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">|8</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">|9</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">|10</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">|11</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">|12</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">|13</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">|14</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">|15</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">|16</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">|17</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">|18</p></body></html>"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionNew_File.setText(_translate("MainWindow", "New File"))
        self.actionNew_Windows.setText(_translate("MainWindow", "New Window"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File"))
        self.actionSave_File.setText(_translate("MainWindow", "Save File"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
