# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'compiler.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(809, 601)
        MainWindow.setStyleSheet("background-color: rgb(192, 191, 188);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 0, 791, 81))
        self.frame.setStyleSheet("background-color: Black;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 10, 201, 61))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 italic 35pt \"Ubuntu\";\n"
"")
        self.label.setObjectName("label")
        self.lex_button = QtWidgets.QPushButton(self.frame)
        self.lex_button.setGeometry(QtCore.QRect(250, 20, 181, 41))
        self.lex_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lex_button.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"")
        self.lex_button.setObjectName("lex_button")
        self.synt_button = QtWidgets.QPushButton(self.frame)
        self.synt_button.setGeometry(QtCore.QRect(480, 20, 181, 41))
        self.synt_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.synt_button.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"")
        self.synt_button.setObjectName("synt_button")
        Ui_MainWindow.TInput = QtWidgets.QTextEdit(self.centralwidget)
        Ui_MainWindow.TInput.setGeometry(QtCore.QRect(10, 90, 791, 291))
        Ui_MainWindow.TInput.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"")
        Ui_MainWindow.TInput.setObjectName("TInput")
        Ui_MainWindow.TOutput = QtWidgets.QTextEdit(self.centralwidget)
        Ui_MainWindow.TOutput.setGeometry(QtCore.QRect(10, 390, 791, 171))
        Ui_MainWindow.TOutput.setStyleSheet("background-color: white;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"\n"
"")
        Ui_MainWindow.TOutput.setObjectName("TOutput")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 809, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.bar_newfile = QtWidgets.QAction(MainWindow)
        self.bar_newfile.setObjectName("bar_newfile")
        self.bar_new_window = QtWidgets.QAction(MainWindow)
        self.bar_new_window.setObjectName("bar_new_window")
        self.bar_openfile = QtWidgets.QAction(MainWindow)
        self.bar_openfile.setObjectName("bar_openfile")
        self.bar_savefile = QtWidgets.QAction(MainWindow)
        self.bar_savefile.setObjectName("bar_savefile")
        self.bar_copy = QtWidgets.QAction(MainWindow)
        self.bar_copy.setObjectName("bar_copy")
        self.bar_paste = QtWidgets.QAction(MainWindow)
        self.bar_paste.setObjectName("bar_paste")
        self.bar_cut = QtWidgets.QAction(MainWindow)
        self.bar_cut.setObjectName("bar_cut")
        self.menuFile.addAction(self.bar_newfile)
        self.menuFile.addAction(self.bar_new_window)
        self.menuFile.addAction(self.bar_openfile)
        self.menuFile.addAction(self.bar_savefile)
        self.menuEdit.addAction(self.bar_copy)
        self.menuEdit.addAction(self.bar_paste)
        self.menuEdit.addAction(self.bar_cut)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Compiler"))
        self.lex_button.setText(_translate("MainWindow", "Analyse Lexical"))
        self.synt_button.setText(_translate("MainWindow", "Analyse Synatxique"))
        Ui_MainWindow.TInput.setPlaceholderText(_translate("MainWindow", "Write Your Code Here..."))
        Ui_MainWindow.TOutput.setPlaceholderText(_translate("MainWindow", "Output"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.bar_newfile.setText(_translate("MainWindow", "New File"))
        self.bar_new_window.setText(_translate("MainWindow", "New Window"))
        self.bar_openfile.setText(_translate("MainWindow", "Open File"))
        self.bar_savefile.setText(_translate("MainWindow", "Save File"))
        self.bar_copy.setText(_translate("MainWindow", "Copy"))
        self.bar_paste.setText(_translate("MainWindow", "Paste"))
        self.bar_cut.setText(_translate("MainWindow", "Cut"))
